"""
Physics sanity check for every report generated by this project.

Two layers of checking, both using ONLY basic electromagnetics -- no FEMM,
no rail, no fitted constants:

1. REFERENCE COIL MODEL. A bare air-core coil defined by inner radius ri,
   outer radius ro, axial length l and wire packing fraction:
     * turns from geometry:      N = pf * (ro-ri) * l / (pi * a_w^2)
     * inductance (Wheeler's multilayer formula, ~1-2% accurate) cross-checked
       against the single-loop formula used throughout this repo
     * DC + AC resistance (skin effect), quality factor Q = wL/R
     * resonant capacitor C = 1/(w^2 L) and its peak voltage V = Ip*w*L
     * coil-to-coil mutual inductance via the magnetic-dipole approximation
       for two coplanar (side-by-side) loops:  M = mu0*pi*N1*N2*r1^2*r2^2/(4 d^3)
   This gives order-of-magnitude expectations that any report must respect.

2. REPORT AUDITS. Each CSV/JSON in reports/ is checked against identities
   that must hold regardless of the model that produced it:
     * open-circuit induction:   V_rx = w * flux_rx           (AC FEMM rows)
     * linearity:                M independent of drive current
     * turn scaling:             M(N)/M(N0) = (N/N0)^2        (FEMM-verified law)
     * resonance:                C = 1/(w^2 L),  V_cap = Ip*w*L = Ip/(w*C)
     * detection dip arithmetic: dip% = (M0-M1)/M0
     * analytic outputs reproduce exactly from the config anchor
     * DOE optimum lies inside the sampled grid

Writes reports/sanity_check_report.md and exits non-zero if any check FAILS.
"""
import sys, os

# Paths come from config (BASE_DIR / OUTPUT_DIR / FEM_FILE), not from this
# script's own directory -- the script lives in a subfolder of the project.
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import json
import math
import os
import re
import sys

import numpy as np
import pandas as pd

import config

# Permeability of free space and the resistivity of copper now come from
# config (config.MU0 / config.RHO_COPPER) and are used directly at every site.

# ================  REFERENCE COIL (all values from config)  ==================
# These were local literals; they are now the canonical coil geometry, so the
# hand-check model and the FEM model can never describe different hardware.
RI = config.COIL_INNER_RADIUS_M    # inner radius (m)
RO = config.COIL_OUTER_RADIUS_M    # outer radius (m)  -> mean radius 35 mm = config value
LEN = config.COIL_LENGTH_M         # axial length of winding (m)
PACKING = config.PACKING_FRACTION  # wire packing fraction of the winding window
WIRE_D = config.WIRE_DIAMETER_M    # wire diameter (m), 18 AWG to match the FEMM blocks
FREQ = config.FREQUENCY_HZ
IP = config.TX_CURRENT_MAG
# =============================================================================

# Every check appends one entry here; the tail of the script turns the list
# into the markdown report and sets the process exit code.
results = []          # (status, section, name, detail)


def record(status, section, name, detail=""):
    results.append((status, section, name, detail))
    print(f"[{status:4}] {section}: {name}" + (f" -- {detail}" if detail else ""))


def check(section, name, ok, detail=""):
    """Record a pass/fail assertion. Only FAILs affect the exit code."""
    record("PASS" if ok else "FAIL", section, name, detail)


def info(section, name, detail):
    record("INFO", section, name, detail)


def skip(section, name, detail):
    record("SKIP", section, name, detail)


def rel_err(a, b):
    """Relative error of `a` against reference `b`, safe when b is zero."""
    if b == 0:
        return abs(a)
    return abs(a - b) / abs(b)


def ac_factor(a_w, freq):
    """Same skin-effect model used across the repo; returns (factor, delta).

    `delta` is the skin depth -- at AC the current crowds into a surface layer
    of roughly that thickness, so the effective conducting cross-section
    shrinks and resistance rises. Multiply a DC resistance by `factor`.
    """
    # Material constants from config -- one definition for the whole project.
    delta = math.sqrt(config.RHO_COPPER / (math.pi * freq * config.MU0))
    x = a_w / delta
    if x < 1.0:
        return 1.0 + x**4 / 48.0, delta
    return x / 2.0 + 0.75 + 3.0 / (32.0 * x), delta


def loop_L(N, r, a_w):
    """Single current-loop formula used throughout the repo (valid when the
    winding bundle is small compared to the coil radius)."""
    return config.MU0 * N**2 * r * (math.log(8 * r / a_w) - 2.0)


def wheeler_L(N, r_mean, length, depth):
    """Wheeler's multilayer air-coil formula (metric form), henries.

    An empirical fit (~1-2% accurate) for a real winding that has physical
    axial length and radial depth, unlike loop_L above which idealises the
    whole winding as one filament. The two therefore disagree by a factor of
    order 1.5-2x for a chunky bundle; they are cross-checked, not equated.
    """
    # Constant = 0.8 / 0.0254. Wheeler published the formula in inches with a
    # 0.8 coefficient; converting to metres divides once by 0.0254 because the
    # numerator gains (1/0.0254)^2 and the denominator (1/0.0254). The exact
    # 31.4961 is used rather than the rounded 31.6 so this matches the hand
    # derivation in sanity_check.md digit for digit.
    return 31.4961e-6 * N**2 * r_mean**2 / (6 * r_mean + 9 * length + 10 * depth)


def dipole_M_coplanar(N1, N2, r1, r2, d):
    """Mutual inductance of two coplanar (side-by-side) loops, dipole approx.
    The equatorial dipole field is half the on-axis field, hence the /4."""
    return config.MU0 * math.pi * N1 * N2 * r1**2 * r2**2 / (4 * d**3)


# ---------------------------------------------------------------------------
# 1. Reference coil model
# ---------------------------------------------------------------------------
SEC = "reference coil"
# Turns implied purely by geometry: how many wire cross-sections of area
# pi*a_w^2 fit into the winding window, derated by the packing fraction.
a_w = WIRE_D / 2
r_mean = (RI + RO) / 2
depth = RO - RI
# The turn count now comes from config: config.TURNS_EXACT is exactly the
# PACKING * (depth * LEN) / (pi * a_w^2) formula above, and BASELINE_TURNS is
# that rounded to a whole turn. Using the INTEGER here keeps Wheeler's formula
# and the FEMM self-check below on the SAME turn count -- FEMM can only wind a
# whole number of turns, so comparing it against a fractional N was unfair.
N_geom = config.BASELINE_TURNS
info(SEC, "geometry", f"ri={RI*1e3:.0f} mm, ro={RO*1e3:.0f} mm, l={LEN*1e3:.0f} mm, "
     f"pf={PACKING}, wire d={WIRE_D*1e3:.3f} mm -> N = {N_geom:.0f} turns")

L_wh = wheeler_L(N_geom, r_mean, LEN, depth)
L_lp = loop_L(N_geom, r_mean, a_w)
info(SEC, "inductance", f"Wheeler L = {L_wh*1e3:.3f} mH, loop-formula L = {L_lp*1e3:.3f} mH "
     f"(ratio {L_lp/L_wh:.2f}; loop formula assumes a thin bundle, so a factor "
     f"of ~1.5-2x spread at this aspect ratio is expected)")
check(SEC, "repo loop formula within 3x of Wheeler", 1/3 < L_lp / L_wh < 3,
      "if this failed, one of the two L models would be misapplied")

# Electrical properties of that coil: wire length -> DC resistance, then the
# AC correction, the quality factor Q = wL/R, the capacitor that resonates it
# (C = 1/(w^2 L)) and the peak voltage that capacitor would have to withstand.
lwire = N_geom * 2 * math.pi * r_mean
R_dc = config.RHO_COPPER * lwire / (math.pi * a_w**2)
fac, delta = ac_factor(a_w, FREQ)
R_ac = R_dc * fac
w = config.OMEGA                       # 2*pi*config.FREQUENCY_HZ, from config
Q = w * L_wh / R_ac
C_res = 1 / (w**2 * L_wh)
V_cap = IP * w * L_wh
info(SEC, "electrical", f"wire {lwire:.1f} m, Rdc={R_dc:.3f} ohm, Rac={R_ac:.3f} ohm "
     f"(skin depth {delta*1e3:.3f} mm), Q={Q:.0f}, C_res={C_res*1e9:.2f} nF, "
     f"V_cap={V_cap:.0f} V pk at Ip={IP} A")
check(SEC, "skin depth < wire radius at operating frequency", delta < a_w,
      f"delta={delta*1e3:.3f} mm vs a={a_w*1e3:.3f} mm -- AC resistance correction matters")

# Coil separation from the model geometry (center-to-center), from config
d_sep = config.COIL_SEPARATION_M
# Both coils carry the canonical baseline turn count.
M_dip_base = dipole_M_coplanar(config.BASELINE_TURNS, config.BASELINE_TURNS,
                               config.COIL_RADIUS_M, config.COIL_RADIUS_M, d_sep)
info(SEC, f"free-space M estimate ({config.BASELINE_TURNS}/{config.BASELINE_TURNS} turns)",
     f"coplanar dipole M = {M_dip_base*1e6:.2f} uH at d = {d_sep*1e3:.1f} mm "
     f"(overestimates somewhat at d/r = {d_sep/config.COIL_RADIUS_M:.1f})")

# FEMM depth caveat -- the single most important scale factor in the project
fem_depth_mm = None
try:
    with open(config.FEM_FILE) as f:
        for line in f:
            m = re.match(r"\[Depth\]\s*=\s*([0-9.eE+-]+)", line)
            if m:
                fem_depth_mm = float(m.group(1))
                break
except OSError:
    pass
if fem_depth_mm is not None:
    check(SEC, "model depth matches config.COIL_DEPTH_MM",
          abs(fem_depth_mm - config.COIL_DEPTH_MM) < 1e-9,
          f".FEM header {fem_depth_mm:g} mm vs config {config.COIL_DEPTH_MM:g} mm -- "
          "these must agree or absolute FEMM numbers are mis-scaled")
    info(SEC, "depth scaling",
         f"2D planar model solved at Depth = {config.COIL_DEPTH_MM:g} mm (the real coil "
         f"axial length), so FEMM fluxes/M/voltages are absolute physical values. "
         f"M0 = {config.M0_UH:.3f} uH vs {M_dip_base*1e6:.2f} uH point-dipole estimate "
         f"(ratio {config.M0_UH*1e-6/M_dip_base:.2f}x).")
    # The point-dipole formula is an ORDER-OF-MAGNITUDE cross-check, not a
    # strict bound. It treats each coil as a point at its centre, so at modest
    # d/R it UNDERSTATES the coupling of a real extended winding: the facing
    # conductor bundles are far closer than the centre-to-centre distance
    # (here the near bundles are ~94 mm apart while the centres are 164 mm).
    # Working against that, the steel rail shields flux at AC. The two effects
    # push opposite ways, so the test is a generous factor-of-3 band -- wide
    # enough to allow either, tight enough to catch a mis-scaled solve.
    ratio = config.M0_UH * 1e-6 / M_dip_base
    check(SEC, "FEMM M0 within a factor of 3 of the point-dipole estimate",
          1.0 / 3.0 < ratio < 3.0,
          f"ratio {ratio:.2f}x at d/R = {d_sep/config.COIL_RADIUS_M:.1f}; "
          "extended windings couple more than point dipoles, the rail shields "
          "-- a value outside this band means the solve is mis-scaled")
else:
    skip(SEC, "FEMM depth check", "could not read [Depth] from the .FEM file")

# Config self-consistency
check(SEC, "config A_REF matches pi*r^2", rel_err(config.A_REF_M2, math.pi * config.COIL_RADIUS_M**2) < 1e-6)

# ---------------------------------------------------------------------------
# 1b. FEMM SELF-CHECK: solve the reference coil in FEMM (axisymmetric, no
# rail, nothing else) and compare its inductance against Wheeler's formula.
# If these agree, the solver setup (units, materials, circuit turns) is
# trustworthy. Skipped automatically when FEMM is not installed.
# ---------------------------------------------------------------------------
SEC = "FEMM self-check (known coil)"


def femm_selfcheck_L():
    import femm
    femm.openfemm(1)                     # 1 = hide the GUI window
    try:
        femm.newdocument(0)              # magnetics problem
        femm.mi_probdef(0, "millimeters", "axi", 1e-8, 0, 30)
        ri, ro, zl = RI * 1e3, RO * 1e3, LEN * 1e3
        z0, z1 = -zl / 2, zl / 2
        for (x, y) in [(ri, z0), (ro, z0), (ro, z1), (ri, z1)]:
            femm.mi_addnode(x, y)
        femm.mi_addsegment(ri, z0, ro, z0)
        femm.mi_addsegment(ro, z0, ro, z1)
        femm.mi_addsegment(ro, z1, ri, z1)
        femm.mi_addsegment(ri, z1, ri, z0)
        femm.mi_getmaterial("Copper")
        femm.mi_getmaterial("Air")
        # 1 A, series circuit. LOCAL literal on purpose: this is a unit probe
        # current for L = flux-linkage / current, not the TX drive level, so it
        # must NOT follow config.TX_CURRENT_MAG.
        femm.mi_addcircprop("selfL", 1.0, 1)
        cx = (ri + ro) / 2
        femm.mi_addblocklabel(cx, 0)
        femm.mi_selectlabel(cx, 0)
        femm.mi_setblockprop("Copper", 1, 0, "selfL", 0, 1, round(N_geom))
        femm.mi_clearselected()
        femm.mi_makeABC(7, 250, 0, 0, 0)       # open boundary, R = 250 mm
        # Air label at (5, 100) mm -- a mesh-label COORDINATE inside the open
        # boundary, not a turn count. Stays local.
        femm.mi_addblocklabel(5, 100)          # air, between coil and boundary
        femm.mi_selectlabel(5, 100)
        femm.mi_setblockprop("Air", 1, 0, "<None>", 0, 0, 0)
        femm.mi_clearselected()
        femm.mi_saveas(os.path.join(config.BASE_DIR, "_selfcheck.fem"))
        femm.mi_analyze(1)
        femm.mi_loadsolution()
        props = femm.mo_getcircuitproperties("selfL")
        L = abs(props[2]) / abs(props[0])      # flux linkage / current
        femm.mo_close()
        femm.mi_close()
        return L
    finally:
        femm.closefemm()


try:
    import femm as _femm_probe            # noqa: F401 -- availability probe
    L_fem = femm_selfcheck_L()
    info(SEC, "measured", f"FEMM (axisymmetric, N={N_geom:.0f}) L = {L_fem*1e3:.3f} mH "
         f"vs Wheeler {L_wh*1e3:.3f} mH ({rel_err(L_fem, L_wh)*100:.1f}% apart) "
         f"vs loop formula {L_lp*1e3:.3f} mH")
    check(SEC, "FEMM matches Wheeler's formula (10%)", rel_err(L_fem, L_wh) < 0.10,
          "units, circuit-turns handling and solver setup are trustworthy" if
          rel_err(L_fem, L_wh) < 0.10 else "solver setup disagrees with textbook physics")
except ImportError:
    skip(SEC, "FEMM matches Wheeler's formula", "pyfemm not installed")
except Exception as e:
    skip(SEC, "FEMM matches Wheeler's formula", f"FEMM run failed: {e}")

# ---------------------------------------------------------------------------
# 2. FEMM property sweep CSV
# ---------------------------------------------------------------------------
SEC = "coil_parameter_sweep_femm.csv"
path = os.path.join(config.OUTPUT_DIR, "coil_parameter_sweep_femm.csv")
if os.path.exists(path):
    df = pd.read_csv(path)
    w20 = config.OMEGA                 # 2*pi*config.FREQUENCY_HZ, from config
    bad = df[abs(df.RX_Voltage_V - w20 * df.RX_Flux_Wb) / (w20 * df.RX_Flux_Wb) > 0.01]
    check(SEC, "open-circuit induction V_rx = w*flux (every row, 1%)", bad.empty,
          f"{len(df) - len(bad)}/{len(df)} rows obey Faraday's law")
    check(SEC, "TX current equals requested drive", (abs(df.TX_Current_A - df.Drive_Current_A) < 1e-6).all())
    piv = df.groupby("Turns").Mutual_Inductance_uH.mean()
    # The reference row is the canonical baseline turn count from config, which
    # is also the row config.M0_UH was measured from.
    if config.BASELINE_TURNS in piv.index:
        errs = {int(n): rel_err(piv[n] / piv[config.BASELINE_TURNS],
                                (n / config.BASELINE_TURNS) ** 2) for n in piv.index}
        worst = max(errs.values())
        check(SEC, "M follows N^2 turn scaling (12%)", worst < 0.12,
              f"ratios vs (N/{config.BASELINE_TURNS})^2: "
              + ", ".join(f"N={n}: {e*100:.1f}%" for n, e in errs.items()))
        check(SEC, f"config.M0_UH matches the {config.BASELINE_TURNS}-turn FEMM row (1%)",
              rel_err(config.M0_UH, piv[config.BASELINE_TURNS]) < 0.01,
              f"config {config.M0_UH:.5f} vs CSV {piv[config.BASELINE_TURNS]:.5f} uH")
    lin = df.groupby("Turns").Mutual_Inductance_uH.agg(lambda s: (s.max() - s.min()) / s.mean())
    check(SEC, "M independent of drive current (linearity, 0.5%)", (lin < 0.005).all(),
          f"max spread {lin.max()*100:.3f}%")
else:
    skip(SEC, "all checks", "file missing")

# ---------------------------------------------------------------------------
# 3. Frequency sweep CSV
# ---------------------------------------------------------------------------
SEC = "frequency_sweep_femm.csv"
path = os.path.join(config.OUTPUT_DIR, "frequency_sweep_femm.csv")
if os.path.exists(path):
    df = pd.read_csv(path)
    wcol = 2 * math.pi * df.Frequency_Hz
    bad = df[abs(df.RX_Voltage_V - wcol * df.RX_Flux_Wb) / (wcol * df.RX_Flux_Wb) > 0.01]
    check(SEC, "V_rx = w*flux at every frequency (1%)", bad.empty,
          f"{len(df) - len(bad)}/{len(df)} rows pass")
    spread = (df.Mutual_Inductance_uH.max() - df.Mutual_Inductance_uH.min()) / df.Mutual_Inductance_uH.mean()
    check(SEC, "M varies smoothly with frequency (<25% over 10-20 kHz)", spread < 0.25,
          f"spread {spread*100:.1f}% (eddy currents in the rail cause a mild drift; "
          "a jump would mean a broken solve)")
    check(SEC, "L_TX positive and finite", (df.L_TX_uH > 0).all() & np.isfinite(df.L_TX_uH).all())
else:
    skip(SEC, "all checks", "file missing")

# ---------------------------------------------------------------------------
# 4. Analytic sweep CSV (must reproduce exactly from the config anchor)
# ---------------------------------------------------------------------------
SEC = "coil_parameter_sweep.csv"
path = os.path.join(config.OUTPUT_DIR, "coil_parameter_sweep.csv")
if os.path.exists(path):
    df = pd.read_csv(path)
    N = df["Coil_Turns (Np=Ns)"]
    sc = df.Area_Scale_Factor
    M_exp = config.M0_UH * (N / config.BASELINE_TURNS) ** 2 * sc * sc
    max_err = np.max(np.abs(df.Mutual_Inductance_uH - M_exp) / M_exp)
    check(SEC, "M reproduces from config anchor (0.1%)", max_err < 1e-3,
          f"max err {max_err * 100:.4f}%")
    w20 = config.OMEGA                 # 2*pi*config.FREQUENCY_HZ, from config
    Vs_exp = 2 * w20 * M_exp * 1e-6 * df.Primary_Current_Peak_A
    check(SEC, "Vs_pp = 2*w*M*Ip (0.1%)",
          np.max(np.abs(df.Resulting_Secondary_Voltage_Vpp - Vs_exp) / Vs_exp) < 1e-3)
    check(SEC, "area column = A_REF * scale", np.max(np.abs(df.Primary_Area_m2 - config.A_REF_M2 * sc)) < 1e-9)
else:
    skip(SEC, "all checks", "file missing")

# ---------------------------------------------------------------------------
# 5. optimal_design.json (air-core design table)
# ---------------------------------------------------------------------------
SEC = "optimal_design.json"
path = os.path.join(config.OUTPUT_DIR, "optimal_design.json")
if os.path.exists(path):
    with open(path) as f:
        od = json.load(f)
    rec = od["recommended"]
    f_op = rec["f_kHz"] * 1e3
    w_op = 2 * math.pi * f_op
    a_od = rec["wire_radius_mm"] * 1e-3
    r_od = rec["coil_dia_mm"] / 2 * 1e-3
    ok_rows, n_rows = 0, 0
    # Every row must be internally consistent: L from the single-loop
    # formula, M from the N^2 anchor scaling, Cp the resonant capacitor
    # 1/(w^2 L), the capacitor peak voltage Ip*w*L within its rating, and the
    # open-circuit receiver voltage Vrx = w*M*Ip (Faraday).
    for row in od["table"]:
        n_rows += 1
        N = row["N"]
        L = row["L_mH"] * 1e-3
        M = row["M_uH"] * 1e-6
        good = (
            rel_err(L, loop_L(N, r_od, a_od)) < 0.01
            and rel_err(M, config.M0_H * (N / config.BASELINE_TURNS) ** 2) < 0.01
            and rel_err(row["Cp_nF"] * 1e-9, 1 / (w_op**2 * L)) < 0.01
            and rec["Ip_A"] * w_op * L <= row["Vcap"] * 1.001
            and rel_err(row["Vrx_oc_mV"] * 1e-3, w_op * M * rec["Ip_A"]) < 0.01
        )
        ok_rows += good
    check(SEC, "every row obeys L/M/C/Vcap/Vrx identities (1%)", ok_rows == n_rows,
          f"{ok_rows}/{n_rows} rows pass")
    check(SEC, "recommended row: cap voltage within its rating",
          rec["Ip_A"] * w_op * rec["L_mH"] * 1e-3 <= rec["Vcap"] * 1.001,
          f"V_cap = {rec['Ip_A'] * w_op * rec['L_mH'] * 1e-3:.0f} V vs {rec['Vcap']} V class")
    check(SEC, "recommended Q*Vrx_oc = Vrx_tuned (1%)",
          rel_err(rec["Vrx_tuned_V"], rec["Q"] * rec["Vrx_oc_mV"] * 1e-3) < 0.01)
else:
    skip(SEC, "all checks", "file missing")

# ---------------------------------------------------------------------------
# 6. wheel_dip.json (detection dip)
# ---------------------------------------------------------------------------
SEC = "wheel_dip.json"
path = os.path.join(config.OUTPUT_DIR, "wheel_dip.json")
if os.path.exists(path):
    with open(path) as f:
        wd = json.load(f)
    dip_exp = (wd["M_no_wheel_uH"] - wd["M_wheel_uH"]) / wd["M_no_wheel_uH"] * 100
    check(SEC, "dip arithmetic (M0-M1)/M0", rel_err(wd["dip_pct"], dip_exp) < 1e-6,
          f"stored {wd['dip_pct']:.2f}% vs recomputed {dip_exp:.2f}%")
    check(SEC, "wheel reduces coupling (M1 < M0)", wd["M_wheel_uH"] < wd["M_no_wheel_uH"],
          f"{wd['M_no_wheel_uH']:.4f} -> {wd['M_wheel_uH']:.4f} uH")
    if wd["RXv_no_wheel"] > 0:
        check(SEC, "voltage ratio tracks M ratio (2%)",
              rel_err(wd["RXv_wheel"] / wd["RXv_no_wheel"],
                      wd["M_wheel_uH"] / wd["M_no_wheel_uH"]) < 0.02,
              "for a fixed-current TX drive, V_rx must scale with M")
else:
    skip(SEC, "all checks", "file missing")

# ---------------------------------------------------------------------------
# 7. DOE / RSM result
# ---------------------------------------------------------------------------
SEC = "doe_rsm_result.json"
path = os.path.join(config.OUTPUT_DIR, "doe_rsm_result.json")
if os.path.exists(path):
    with open(path) as f:
        doe = json.load(f)
    opt = doe["optimum"]
    inx = min(config.distance_shifts) <= opt["x"] <= max(config.distance_shifts)
    iny = min(config.height_shifts) <= opt["y"] <= max(config.height_shifts)
    int_ = min(config.tilt_angles) <= opt["theta"] <= max(config.tilt_angles)
    check(SEC, "optimum lies inside the sampled DOE grid", inx and iny and int_,
          f"x={opt['x']:.2f}, y={opt['y']:.2f}, theta={opt['theta']:.2f}")
    Ms = [r["M_uH"] for r in doe["runs"]]
    check(SEC, "verified optimum >= 95% of best sampled run",
          doe["optimum_M_uH"] >= 0.95 * max(Ms),
          f"optimum {doe['optimum_M_uH']:.4f} vs best sampled {max(Ms):.4f} uH")
else:
    skip(SEC, "all checks", "not yet generated (run the fixed axle.py)")

# ---------------------------------------------------------------------------
# 8. Legacy notebook sweep CSV
# ---------------------------------------------------------------------------
SEC = "axle_counter_sweep_data.csv"
path = os.path.join(config.OUTPUT_DIR, "axle_counter_sweep_data.csv")
if os.path.exists(path):
    df = pd.read_csv(path)
    w_all = 2 * math.pi * df.Frequency_Hz
    vc_exp = df.Peak_Current_A / (w_all * df.Capacitor_Value_F)
    check(SEC, "V_cap = I/(w*C) at resonance (1%)",
          np.max(np.abs(df.Capacitor_Voltage_Peak_V - vc_exp) / vc_exp) < 0.01)
    check(SEC, "uncompensated V >= resonant V on every row",
          (df.Uncomp_Voltage_Peak_V >= df.Resonant_Voltage_Peak_V - 1e-9).all())
else:
    skip(SEC, "all checks", "file missing")

# ---------------------------------------------------------------------------
# 9. FEMM live-run text log (V = w*flux in the AC section)
# ---------------------------------------------------------------------------
SEC = "femm_live_result.txt"
path = os.path.join(config.OUTPUT_DIR, "femm_live_result.txt")
if os.path.exists(path):
    try:
        txt = open(path).read()
        # Frequency label is derived from config, not hardcoded -- otherwise
        # changing config.FREQUENCY_HZ makes this check silently SKIP.
        m = re.search(r"TIME-HARMONIC \(f=%dkHz\)\]\s*"
                      r".*?RX flux linkage\s*:\s*([0-9.eE+-]+)\s*Wb"
                      r".*?RX induced voltage:\s*([0-9.eE+-]+)\s*V"
                      % round(config.FREQUENCY_HZ / 1e3), txt, re.S)
        if m:
            flux, volt = float(m.group(1)), float(m.group(2))
            w20 = config.OMEGA         # 2*pi*config.FREQUENCY_HZ, from config
            check(SEC, "AC section obeys V = w*flux (1%)", rel_err(volt, w20 * flux) < 0.01,
                  f"{volt:.6f} V vs w*flux = {w20*flux:.6f} V")
        else:
            skip(SEC, "V = w*flux", "no time-harmonic section found in log")
    except Exception as e:
        skip(SEC, "V = w*flux", f"parse error: {e}")
else:
    skip(SEC, "all checks", "file missing")

# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------
# Tally, write the markdown report, and exit non-zero if anything FAILed so
# the script can be used as a build/CI gate.
n_pass = sum(1 for s, *_ in results if s == "PASS")
n_fail = sum(1 for s, *_ in results if s == "FAIL")
n_skip = sum(1 for s, *_ in results if s == "SKIP")
print(f"\n=== SANITY CHECK: {n_pass} passed, {n_fail} failed, {n_skip} skipped ===")

out_md = os.path.join(config.OUTPUT_DIR, "sanity_check_report.md")
with open(out_md, "w", encoding="utf-8") as f:
    f.write("# Sanity Check Report\n\n")
    f.write(f"Reference coil: ri={RI*1e3:.0f} mm, ro={RO*1e3:.0f} mm, l={LEN*1e3:.0f} mm, "
            f"packing={PACKING}, wire d={WIRE_D*1e3:.3f} mm, f={FREQ/1e3:.0f} kHz, Ip={IP} A\n\n")
    f.write(f"**Result: {n_pass} passed / {n_fail} failed / {n_skip} skipped**\n\n")
    cur = None
    for status, section, name, detail in results:
        if section != cur:
            f.write(f"\n## {section}\n\n")
            cur = section
        mark = {"PASS": "✅", "FAIL": "❌", "INFO": "ℹ️", "SKIP": "⏭️"}[status]
        f.write(f"- {mark} **{name}**" + (f" — {detail}" if detail else "") + "\n")
print(f"Report written to {out_md}")
sys.exit(1 if n_fail else 0)
